services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - LOG_LEVEL=${FLARESOLVERR_LOG_LEVEL}
      - LOG_HTML=${FLARESOLVERR_LOG_HTML}
      - LANG=${FLARESOLVERR_LANG}
      - TZ=${TIMESONE}
