services:
  ###########################################################################
  ###########################################################################
  ##
  ##  Docker Compose File: Buildarr (callum027)
  ##  Function: Buildarr is used to fill in the configuration of other *Arr services programatically
  ##
  ##  Documentation: https://buildarr.github.io/
  ##
  ###########################################################################
  ###########################################################################
  buildarr:
    image: callum027/buildarr:latest
    container_name: buildarr
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - default # call apis of containers on this network
    depends_on:
      - gluetun # VPN some containers are using
      - prowlarr # Configured Prowlarr Instance
      - flaresolverr # FlareSolverr proxy for prowlarr
      - radarr # Configured Radarr Instance (Movies)
    # - radarr-anime # Configured Radarr Instance (Movies - Anime)
    # - sonarr # Configured Sonarr Instance (TV Shows)
    # - sonarr-anime # Configured Sonarr Instance (TV Shows - Anime)
    # - lidarr # Configured Lidarr Instance (Music)
    # - readarr # Configured Readarr Instance (Books)
    volumes:
      - ${INSTALL_DIR}/compose/services/buildarr/config:/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMESONE}
      - BUILDARR_LOG_LEVEL=INFO
    labels:
      - com.centurylinklabs.watchtower.enable=true
