services:
  ###########################################################################
  ###########################################################################
  ##
  ##  Docker Compose File: Jellyfin (LinuxServer.io)
  ##  Function: Media Server
  ##
  ##  Documentation: https://jellyfin.org/docs/general/administration/installing#docker
  ##  https://jellyfin.org/docs/general/administration/hardware-acceleration/
  ##
  ###########################################################################
  ###########################################################################
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: "no"
    security_opt:
      - no-new-privileges:true
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    devices:
      - /dev/dri:/dev/dri # for harware transcoding
    volumes:
      - ${INSTALL_DIR}/compose/services/jellyfin/config:/config
      - ${MEDIA_DIR}:/data/media
      - /dev/shm:/data/transcode # Offload transcoding to RAM if you have enough RAM
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK_SET=022
      - TZ=${TIMESONE}
    labels:
      - com.centurylinklabs.watchtower.enable=true
