services:
  # Portainer is a lightweight management UI which allows you to easily manage your Docker host or Swarm cluster
  # https://www.portainer.io/
  # Root Image: ???
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - socket_proxy
    command: -H tcp://socket-proxy:2375 --admin-password-file=/run/secrets/portainer_admin_password --http-enabled
    ports:
      - 9000:9000 # HTTP UI
    volumes:
      - ${INSTALL_DIR}/compose/services/portainer/config:/data
    environment:
      - TZ=${TIMESONE}
    secrets:
      - portainer_admin_password
    labels:
      - com.centurylinklabs.watchtower.enable=true

secrets:
  portainer_admin_password:
    file: ./secrets/portainer_admin_password
