includes:
  #- radarr.yml
  - prowlarr.yml

# Buildarr configuration (all settings have sane default values)
buildarr:
  watch_config: true
  update_Days:
    - "monday"
    - "tuesday"
    - "wednesday"
    - "thursday"
    - "friday"
    - "saturday"
    - "sunday"
  update_time: "03:00"
