# Buildarr configuration (all settings have sane default values)
buildarr:
  watch_config: true
  update_Days:
    - "monday"
    - "tuesday"
    - "wednesday"
    - "thursday"
    - "friday"
    - "saturday"
    - "sunday"
  update_time: "03:00"

# Radarr instance configuration
radarr:
  hotname: localhost
  port: 7878
  protocol: http
  general:
    security:
      authentication: external
    logging:
      log_level: INFO
    analytics:
      send_anonymous_usage_data: false
  ui:
    first_day_of_week: monday
    week_column_header: day-first
    runtime_format: hours-minutes
    short_date_format: slash-day-first
    long_date_format: day-first
    time_format: twentyfour-hour
    show_relative_dates: true
    theme: auto
    enable_color_impaired_mode: false
    movie_info_language: english
    ui_language: english
  settings:
    media_management:
      rename_movies: true
      replace_illegal_characters: true
      colon_replacement: space-dash-space
      standard_movie_format:
        "{Movie CleanTitle} {(Release Year)} [imdbid-{ImdbId}] - {Edition Tags }{[Custom Formats]}
        {[Quality Full]}{[MediaInfo 3D]}{[MediaInfo VideoDynamicRangeType]}{[Mediainfo AudioCodec}
        { Mediainfo AudioChannels]}{[Mediainfo VideoCodec]}{-Release Group}"
      movie_folder_format: "{Movie CleanTitle} ({Release Year})"
      create_missing_movie_folders: false
      delete_empty_folders: false
      skip_free_space_check: false
      minimum_free_space: 100
      use_hardlinks: true
      propers_and_repacks: do-not-prefer
      analyze_video_files: true
      rescan_folder_after_refresh: always
      root_folders:
        delete_unmanaged: true
        definitions:
          - /data/media/movies
    profiles:
      quality_profiles:
        delete_unmanaged: true
        definitions:
          HD Bluray + WEB:
            upgrades_allowed: true
            qualities:
              - Bluray-1080p
              - name: WEB 1080p
                members:
                  - WEBRip-1080p
                  - WEBDL-1080p
              - Bluray-720p
            upgrade_until_quality: Bluray-1080p
            minimum_custom_format_score: 0
            upgrade_until_custom_format_score: 10000
            custom_formats:
              # Movie Versions
              - name: remaster
                score: 25
              - name: 4k-remaster
                score: 25
              - name: criterion-collection
                score: 25
              - name: masters-of-cinema
                score: 25
              - name: vinegar-syndrome
                score: 25
              - name: special-edition
                score: 125
              - name: imax
                score: 800
              - name: imax-enhanced
                score: 800
              # HQ Release Groups
              - name: hd-bluray-tier-01
                score: 1800
              - name: hd-bluray-tier-02
                score: 1750
              - name: hd-bluray-tier-03
                score: 1700
              - name: web-tier-01
                score: 1650
              - name: web-tier-02
                score: 1600
              - name: web-tier-03
                score: 1550
              # Misc
              - name: repack-proper
                score: 5
              - name: repack-2
                score: 6
              - name: repack-3
                score: 7
              # Unwanted
              - name: br-disk
                score: -10000
              - name: lq
                score: -10000
              - name: lq-release-title
                score: -10000
              - name: x265-hd
                score: -10000
              - name: 3d
                score: -10000
              - name: extras
                score: -10000
              - name: av1
                score: -10000
              # Optional
              - name: bad-dual-groups
                score: -10000
              - name: evo-no-webdl
                score: -10000
              - name: no-risgroup
                score: -10000
              - name: obfuscated
                score: -10000
              - name: retags
                score: -10000
              - name: scene
                score: -10000
              # General Streaming Services
              - name: amzn
                score: 0
              - name: atvp
                score: 0
              - name: bcore
                score: 15
              - name: crit
                score: 20
              - name: dsnp
                score: 0
              - name: hbo
                score: 0
              - name: hmax
                score: 0
              - name: hulu
                score: 0
              - name: it
                score: 0
              - name: max
                score: 0
              - name: ma
                score: 20
              - name: nf
                score: 0
              - name: pmtp
                score: 0
              - name: pcok
                score: 0
              - name: stan
                score: 0
            language: Original
      delay_profiles:
        definitions:
          - preferred_protocol: torrent-prefer
            usenet_delay: 0
            torrent_delay: 1440
            bypass_if_highest_quality: true
            tags: []
        delete_unmanaged: false
    quality:
      trash_id: aed34b9f60ee115dfa7918b742336277
    notifications:
      delete_unmanaged: false
      definitions: {}
    custom_formats:
      delete_unmanaged: true
      definitions:
        # Movie Versions
        remaster:
          trash_id: 570bc9ebecd92723d2d21500f4be314c
        4k-remaster:
          trash_id: eca37840c13c6ef2dd0262b141a5482f
        criterion-collection:
          trash_id: e0c07d59beb37348e975a930d5e50319
        masters-of-cinema:
          trash_id: 9d27d9d2181838f76dee150882bdc58c
        vinegar-syndrome:
          trash_id: db9b4c4b53d312a3ca5f1378f6440fc9
        special-edition:
          trash_id: 957d0f44b592285f26449575e8b1167e
        imax:
          trash_id: eecf3a857724171f968a66cb5719e152
        imax-enhanced:
          trash_id: 9f6cbff8cfe4ebbc1bde14c7b7bec0de

        # HQ Release Groups
        hd-bluray-tier-01:
          trash_id: ed27ebfef2f323e964fb1f61391bcb35
        hd-bluray-tier-02:
          trash_id: c20c8647f2746a1f4c4262b0fbbeeeae
        hd-bluray-tier-03:
          trash_id: 5608c71bcebba0a5e666223bae8c9227
        web-tier-01:
          trash_id: c20f169ef63c5f40c2def54abaf4438e
        web-tier-02:
          trash_id: 403816d65392c79236dcb6dd591aeda4
        web-tier-03:
          trash_id: af94e0fe497124d1f9ce732069ec8c3b

        # Misc
        repack-proper:
          trash_id: e7718d7a3ce595f289bfee26adc178f5
        repack-2:
          trash_id: ae43b294509409a6a13919dedd4764c4
        repack-3:
          trash_id: 5caaaa1c08c1742aa4342d8c4cc463f2

        # Unwanted
        br-disk:
          trash_id: ed38b889b31be83fda192888e2286d83
        lq:
          trash_id: 90a6f9a284dff5103f6346090e6280c8
        lq-release-title:
          trash_id: e204b80c87be9497a8a6eaff48f72905
        x265-hd:
          trash_id: dc98083864ea246d05a42df0d05f81cc
        3d:
          trash_id: b8cd450cbfa689c0259a01d9e29ba3d6
        extras:
          trash_id: 0a3f082873eb454bde444150b70253cc
        av1:
          trash_id: cae4ca30163749b891686f95532519bd

        # Optional
        bad-dual-groups:
          trash_id: b6832f586342ef70d9c128d40c07b872
        evo-no-webdl:
          trash_id: 90cedc1fea7ea5d11298bebd3d1d3223
        no-risgroup:
          trash_id: ae9b7c9ebde1f3bd336a8cbd1ec4c5e5
        obfuscated:
          trash_id: 7357cf5161efbf8c4d5d0c30b4815ee2
        retags:
          trash_id: 5c44f52a8714fdd79bb4d98e2673be1f
        scene:
          trash_id: f537cf427b64c38c8e36298f657e4828

        # General Streaming Services
        amzn:
          trash_id: b3b3a6ac74ecbd56bcdbefa4799fb9df
        atvp:
          trash_id: 40e9380490e748672c2522eaaeb692f7
        bcore:
          trash_id: cc5e51a9e85a6296ceefe097a77f12f4
        crit:
          trash_id: 16622a6911d1ab5d5b8b713d5b0036d4
        dsnp:
          trash_id: 84272245b2988854bfb76a16e60baea5
        hbo:
          trash_id: 509e5f41146e278f9eab1ddaceb34515
        hmax:
          trash_id: 5763d1b0ce84aff3b21038eea8e9b8ad
        hulu:
          trash_id: 526d445d4c16214309f0fd2b3be18a89
        it:
          trash_id: e0ec9672be6cac914ffad34a6b077209
        max:
          trash_id: 6a061313d22e51e0f25b7cd4dc065233
        ma:
          trash_id: 2a6039655313bf5dab1e43523b62c374
        nf:
          trash_id: 170b1d363bd8516fbf3a3eb05d4faff6
        pmtp:
          trash_id: e36a0ba1bc902b26ee40818a1d59b8bd
        pcok:
          trash_id: c9fd353f8f5f1baf56dc601c4cb29920
        stan:
          trash_id: c2863d2a50c9acad1fb50e53ece60817
