includes:
  - ./prowlarr-settings/prowlarr-general.yml
  - ./prowlarr-settings/prowlarr-indexers.yml
  - ./prowlarr-settings/prowlarr-sync-profiles.yml
  - ./prowlarr-settings/prowlarr-tags.yml
  - ./prowlarr-settings/prowlarr-ui.yml

# Prowlarr instance configuration
prowlarr:
  hostname: gluetun
  port: 9696
  protocol: http
  settings:
    notifications:
      definitions: {}
      delete_unmanaged: false
