includes:
  - ./prowlarr-sub-configs/prowlarr-general.yml
  - ./prowlarr-sub-configs/prowlarr-indexers.yml
  - ./prowlarr-sub-configs/prowlarr-sync-profiles.yml
  - ./prowlarr-sub-configs/prowlarr-tags.yml
  - ./prowlarr-sub-configs/prowlarr-ui.yml
  - ./prowlarr-sub-configs/prowlarr-applications.yml
  - ./prowlarr-sub-configs/prowlarr-download-clients.yml

# Prowlarr instance configuration.
prowlarr:
  hostname: gluetun
  port: 9696
  protocol: http
  settings:
    notifications:
      definitions: {}
      delete_unmanaged: false
