# Prowlarr instance configuration
prowlarr:
  hostname: prowlarr
  port: 9696
  protocol: "http"
  general:
    security:
      authentication: external
    logging:
      log_level: INFO
    analytics:
      send_anonymous_usage_data: false
  ui:
    enable_color_impaired_mode: false
    first_day_of_week: monday
    long_date_format: year-first
    short_date_format: word-month-first
    show_relative_dates: true
    theme: auto
    time_format: twentyfour-hour
    ui_language: en
    week_column_header: month-first
  settings:
    tags:
      definitions:
        - "shows"
        - "anime-shows"
        - "movies"
        - "anime-movies"
        - "books"
        - "adult-shows"
        - "adult-movies"
    indexers:
      indexers:
        definitions:
          #1337x: 25
          anirena:
            type: anirena
            enable: true
            sync_profile: Standard
            redirect: false
            priority: 15
            grab_limit: 26
            query_limit: 256
            tags:
              - "anime-shows"
              - "anime-movies"
            fields:
              torrentBaseSettings.seedRatio: 0.1
              prefer_magnet_links: true
          badasstorrents:
            type: badasstorrents
            enable: true
            sync_profile: Standard
            redirect: false
            priority: 35
            grab_limit: 26
            query_limit: 256
            tags:
              - "shows"
              - "movies"
              - "books"
              - "anime-shows"
            fields:
              torrentBaseSettings.seedRatio: 1
              prefer_magnet_links: true
          bangumi-moe:
            type: bangumi-moe
            enable: true
            sync_profile: Standard
            redirect: false
            priority: 50
            grab_limit: 26
            query_limit: 256
            tags:
              - "anime-shows"
              - "anime-movies"
            fields:
              torrentBaseSettings.seedRatio: 0.1
              prefer_magnet_links: true
          #extratorrent-st: 30
          eztv:
            type: eztv
            enable: true
            sync_profile: Standard
            redirect: false
            priority: 20
            grab_limit: 26
            query_limit: 256
            tags:
              - "shows"
            fields:
              torrentBaseSettings.seedRatio: 1
              prefer_magnet_links: true
          limetorrents:
            type: limetorrents
            enable: true
            sync_profile: Standard
            redirect: false
            priority: 40
            grab_limit: 26
            query_limit: 256
            tags:
              - "shows"
              - "movies"
              - "books"
              - "anime-shows"
              - "anime-movies"
            fields:
              torrentBaseSettings.seedRatio: 1
              prefer_magnet_links: true
          thepiratebay:
            type: thepiratebay
            enable: true
            sync_profile: Standard
            redirect: false
            priority: 45
            grab_limit: 26
            query_limit: 256
            tags:
              - "shows"
              - "movies"
              - "books"
            fields:
              torrentBaseSettings.seedRatio: 1
              prefer_magnet_links: true
          therarbg:
            type: therarbg
            enable: true
            sync_profile: Standard
            redirect: false
            priority: 50
            grab_limit: 26
            query_limit: 256
            tags:
              - "shows"
              - "movies"
              - "books"
              - "anime-shows"
              - "anime-movies"
            fields:
              torrentBaseSettings.seedRatio: 1
              prefer_magnet_links: true
          yts:
            type: yts
            enable: true
            sync_profile: Standard
            redirect: false
            priority: 5
            grab_limit: 26
            query_limit: 256
            tags:
              - "movies"
            fields:
              torrentBaseSettings.seedRatio: 3
              prefer_magnet_links: true
          nyaasi:
            type: nyaasi
            enable: true
            sync_profile: Standard
            redirect: false
            priority: 10
            grab_limit: 26
            query_limit: 256
            tags:
              - "anime-shows"
              - "anime-movies"
            fields:
              torrentBaseSettings.seedRatio: 0.1
              prefer_magnet_links: true
    proxies:
      definitions:
        "FlareSolverr":
          type: "flaresolverr"
          host_url: "http://flaresolverr:8191"
          request_timeout: 60
          tags:
            - "shows"
    sync_profiles:
      definitions:
        Standard:
          enable_rss: true
          enable_interactive_search: true
          enable_automatic_search: true
          minimum_seeders: 5
    notifications:
      definitions: {}
      delete_unmanaged: false
