services:
  # qBitorrent-port is used to auto update qbittorrent with gluetun's port-forward value
  qbittorrent-port:
    image: charlocharlie/qbittorrent-port-forward-file:latest
    container_name: qbittorrent-port
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
      - qbittorrent
    volumes:
      - ${INSTALL_DIR}/compose/services/gluetun/config:/config/gluetun:ro
    environment:
      - QBT_USERNAME=${QBT_USER}
      - QBT_PASSWORD=${QBT_PASS}
      - QBT_ADDR=http://localhost:${QBT_EXTERNAL_WEBUI_PORT}
      - PORT_FILE=/config/gluetun/forwarded_port
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - com.centurylinklabs.watchtower.depends-on=gluetun
