services:
  ###########################################################################
  ###########################################################################
  ##
  ##  Docker Compose File: Radarr (LinuxServer.io)
  ##  Function: Movie Library Manager - for Anime
  ##
  ##  Documentation: https://docs.linuxserver.io/images/docker-radarr
  ##
  ###########################################################################
  ###########################################################################
  radarr-anime:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr-anime
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
      - prowlarr
      - deluge
    volumes:
      - ${INSTALL_DIR}/compose/services/radarr-anime/config:/config
      - ${DATA_DIR}:/data
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMESONE}
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - com.centurylinklabs.watchtower.depends-on=gluetun
