#===============================================================================
# Networks
#===============================================================================
networks:
  default:
    driver: bridge

#===============================================================================
# Included services
#===============================================================================
include:
  - ./services/gluten/docker-compose.yaml
  - ./services/qbittorrent/docker-compose.yaml
  - ./services/watchtower/docker-compose.yaml
  - ./services/portainer/docker-compose.yaml
