###########################################################################
###########################################################################
##
##  Docker Compose File: Docker Media Center
##  Function: Everything related to managing a media center
##
##  VPN: Qbittorrent, Prowlarr, FlareSolverr
##
##  Non-VPN: Jellyfin, Radarr, Buildarr, Watchtower
##
###########################################################################
###########################################################################

name: docker-media-center

#===============================================================================
# Networks
#===============================================================================
networks:
  default:
    driver: bridge
  socket_proxy:
    name: socket_proxy
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 192.168.91.0/24

#===============================================================================
# Included services
#===============================================================================
include:
  # CORE
  - ./services/socket-proxy/docker-compose.yaml
  - ./services/gluetun/docker-compose.yaml
  - ./services/watchtower/docker-compose.yaml
  - ./services/dozzle/docker-compose.yaml
  # MEDIA
  - ./services/jellyfin/docker-compose.yaml
  - ./services/qbittorrent/docker-compose.yaml
  - ./services/radarr/docker-compose.yaml
  # UTILITIES
  - ./services/qbittorrent-port/docker-compose.yaml
  - ./services/buildarr/docker-compose.yaml
  - ./services/prowlarr/docker-compose.yaml
  - ./services/flaresolverr/docker-compose.yaml
