name: docker-media-center

#===============================================================================
# Networks
#===============================================================================
networks:
  default:
    driver: bridge
  socket_proxy:
    name: socket_proxy
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 192.168.91.0/24

#===============================================================================
# Included services
#===============================================================================
include:
  # CORE
  - ./services/socket-proxy/docker-compose.yaml
  - ./services/gluten/docker-compose.yaml
  - ./services/watchtower/docker-compose.yaml
  - ./services/portainer/docker-compose.yaml
  - ./services/dozzle/docker-compose.yaml
  # MEDIA
  - ./services/jellyfin/docker-compose.yaml
  - ./services/qbittorrent/docker-compose.yaml
  - ./services/radarr/docker-compose.yaml
