prowlarr:
  settings:
    apps:
      sync_profiles:
        definitions:
          Standard:
            enable_rss: true
            enable_interactive_search: true
            enable_automatic_search: true
            minimum_seeders: 5
          Automatic Search:
            enable_rss: false
            enable_interactive_search: true
            enable_automatic_search: true
            minimum_seeders: 20
          Interactive Search:
            enable_rss: false
            enable_interactive_search: true
            enable_automatic_search: false
            minimum_seeders: 20
