services:
  # qBitorrent is used to download torrents
  # Root Image: Alpine Linux
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    volumes:
      - ${TORRENTS_DIR}:/data/torrents
      - ${INSTALL_DIR}/compose/services/qbittorrent/config:/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMESONE}
      - UMASK_SET=022
      - WEBUI_PORT=8085
    labels:
      - com.centurylinklabs.watchtower.enable=true
