services:
  ###########################################################################
  ###########################################################################
  ##
  ##  Docker Compose File: Gluetun (qmcgaw)
  ##  Function: VPN Client
  ##
  ##  Documentation: https://github.com/qdm12/gluetun/wiki
  ##
  ###########################################################################
  ###########################################################################
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # Gluetun Local Network HTTP proxy
      - 8388:8388/tcp # Gluetun Local Network Shadowsocks
      - 8388:8388/udp # Gluetun Local Network Shadowsocks
      - 8000:8000/tcp # Build-in HTTP control header
      # other container ports
      - ${QBT_EXTERNAL_WEBUI_PORT}:${QBT_CONTAINER_WEBUI_PORT}/tcp # WebUI Portal: qbittorrent (HTTP)
      - ${QBT_EXTERNAL_TORRENTING_PORT}:${QBT_CONTAINER_TORRENTING_PORT} # Torrenting Port: qbittorent
      - ${QBT_EXTERNAL_TORRENTING_PORT}:${QBT_CONTAINER_TORRENTING_PORT}/udp # Torrenting Port: qbittorent (UDP)
      - ${RADARR_EXTERNAL_PORT}:${RADARR_CONTAINER_PORT}/tcp # WebUI Portal: Radarr (HTTP)
      - ${JELLYFIN_EXTERNAL_PORT}:${JELLYFIN_CONTAINER_PORT}/tcp # WebUI Portal: Jellyfin (HTTP)
      - ${PROWLARR_EXTERNAL_PORT}:${PROWLARR_CONTAINER_PORT}/tcp # WebUI Portal: Prowlarr (HTTP)
    volumes:
      - ${INSTALL_DIR}/compose/services/gluetun/config:/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMESONE}
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE}
      - VPN_TYPE=openvpn
      - OPENVPN_USER=${VPN_USER}
      - OPENVPN_PASSWORD=${VPN_PASSWORD}
      - OPENVPN_CIPHERS=AES-256-GCM
      - VPN_PORT_FORWARDING=on
      - VPN_PORT_FORWARDING_STATUS_FILE=/config/forwarded_port
      - UPDATER_PERIOD=24h
      - SERVER_REGIONS=${VPN_REGIONS}
      - FIREWALL_OUTBOUND_SUBNETS=${NETWORK_SUBNET}/24
      - HTTPPROXY=on
    # The container has no recovery logic. Use a healthcheck to catch disconnects.
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 60s
      timeout: 20s
      retries: 5
    labels:
      - com.centurylinklabs.watchtower.enable=true
