radarr:
  instances:
    radarr-anime:
      settings:
        custom_formats:
          delete_unmanaged: true
          definitions:
            anime-bd-tier-01:
              trash_id: fb3ccc5d5cc8f77c9055d4cb4561dded
            anime-bd-tier-02:
              trash_id: 66926c8fa9312bc74ab71bf69aae4f4a
            anime-bd-tier-03:
              trash_id: fa857662bad28d5ff21a6e611869a0ff
            anime-bd-tier-04:
              trash_id: f262f1299d99b1a2263375e8fa2ddbb3
            anime-bd-tier-05:
              trash_id: ca864ed93c7b431150cc6748dc34875d
            anime-bd-tier-06:
              trash_id: 9dce189b960fddf47891b7484ee886ca
            anime-bd-tier-07:
              trash_id: 1ef101b3a82646b40e0cab7fc92cd896
            anime-bd-tier-08:
              trash_id: 6115ccd6640b978234cc47f2c1f2cadc
            anime-we-tier-01:
              trash_id: 8167cffba4febfb9a6988ef24f274e7e
            anime-we-tier-02:
              trash_id: 8526c54e36b4962d340fce52ef030e76
            anime-we-tier-03:
              trash_id: de41e72708d2c856fa261094c85e965d
            anime-we-tier-04:
              trash_id: 9edaeee9ea3bcd585da9b7c0ac3fc54f
            anime-we-tier-05:
              trash_id: 22d953bbe897857b517928f3652b8dd3
            anime-we-tier-06:
              trash_id: a786fbc0eae05afe3bb51aee3c83a9d4
            remux-tier-01:
              trash_id: 3a3ff47579026e76d6504ebea39390de
            remux-tier-02:
              trash_id: 9f98181fe5a3fbeb0cc29340da2a468a
            remux-tier-03:
              trash_id: 8baaf0b3142bf4d94c42a724f034e27a
            web-tier-01:
              trash_id: c20f169ef63c5f40c2def54abaf4438e
            web-tier-02:
              trash_id: 403816d65392c79236dcb6dd591aeda4
            web-tier-03:
              trash_id: af94e0fe497124d1f9ce732069ec8c3b
            anime-raws:
              trash_id: 06b6542a47037d1e33b15aa3677c2365
            anime-lq-groups:
              trash_id: b0fdc5897f68c9a68c70c25169f77447
            unsensored:
              trash_id: 064af5f084a0a24458cc8ecd3220f93f
            v0:
              trash_id: c259005cbaeb5ab44c06eddb4751e70c
            v1:
              trash_id: 5f400539421b8fcf71d51e6384434573
            v2:
              trash_id: 3df5e6dfef4b09bb6002f732bed5b774
            v3:
              trash_id: db92c27ba606996b146b57fbe6d09186
            v4:
              trash_id: d4e5e842fad129a3c097bdb2d20d31a0
            vrv:
              trash_id: 60f6d50cbd3cfc3e9a8c00e3a30c3114
            10bit:
              trash_id: a5d148168c4506b55cf53984107c396e
            anime-dual-audio:
              trash_id: 4a3b087eea2ce012fcc1ce319259a3be
            dubs-only:
              trash_id: b23eae459cc960816f2d6ba84af45055
            vostfr:
              trash_id: 9172b2f683f6223e3a1846427b417a3d
            av1:
              trash_id: cae4ca30163749b891686f95532519bd
