services:
  # Radarr is used to query, add downloads to the download queue and index Movies
  # https://radarr.video/
  # Root Image: Alpine Linux
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - default
    ports:
      - 7878:7878
    volumes:
      - ${INSTALL_DIR}/compose/services/radarr/config:/config
      - ${DOWNLOADS_DIR}:/downloads
      - ${MOVIES_DIR}:/movies
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMESONE}
    labels:
      - com.centurylinklabs.watchtower.enable=true
